services:
  prowlarr-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prowlarr-mcp
    labels:
      - com.centurylinklabs.watchtower.enable=false
    ports:
      - "${PROWLARR_MCP_PORT:-9159}:${PROWLARR_MCP_PORT:-9159}"
    env_file:
      - .env
    volumes:
      - /mnt/cache/appdata/prowlarr-mcp/logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9159/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - jakenet

networks:
  jakenet:
    external: true 